##
# LocalGov Drupal CI
---
services:

  drupal:
    image: localgovdrupal/apache-php:php8.1
    container_name: drupal
    depends_on:
      database:
        condition: service_healthy
      chromedriver:
        condition: service_started
    ports:
      - "80:80"
    environment:
      SIMPLETEST_BASE_URL: 'http://drupal'
      SIMPLETEST_DB: 'mysql://database:database@database/database'
      MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", { "chromeOptions": { "w3c": false } }, "http://chromedriver:4444/wd/hub"]'
      SYMFONY_DEPRECATIONS_HELPER: weak
    extra_hosts:
      - "group-a1.drupal:127.0.0.1"
      - "group-a2.drupal:127.0.0.1"
      - "group-a3.drupal:127.0.0.1"
      - "group-b1.drupal:127.0.0.1"
      - "group-b2.drupal:127.0.0.1"
      - "group-b3.drupal:127.0.0.1"
    volumes:
      - ./html:/var/www/html

  database:
    image: mariadb:10.9.6
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: database
      MARIADB_USER: database
      MARIADB_PASSWORD: database
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 100

  chromedriver:
    image: selenium/standalone-chrome:106.0
    container_name: chromedriver
    environment:
      START_XVBF: 'false'
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm
