##
# LocalGovDrupal CI
---
version: '3'
    
services:

  drupal:
    image: localgovdrupal/apache-php:php7.2
    container_name: drupal
    environment:
      SIMPLETEST_BASE_URL: 'http://drupal'
      SIMPLETEST_DB: 'mysql://database:database@database/database'
      MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--headless", "--no-sandbox", "--disable-dev-shm-usage"]}}, "http://chrome:9515"]'
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html

  database:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: database
      MYSQL_USER: database
      MYSQL_PASSWORD: database
    ports:
      - "3306:3306"

  chrome:
    image: drupalci/webdriver-chromedriver:production
    ulimits:
      core:
        soft: -1
        hard: -1
    ports:
      - "4444:4444"
      - "9515:9515"
    entrypoint:
      - chromedriver
      - "--log-path=/tmp/chromedriver.log"
      - "--verbose"
      - "--whitelisted-ips="
