##
# LocalGov Drupal CI
---
services:

  drupal:
    image: localgovdrupal/apache-php:php8.1
    container_name: drupal
    depends_on:
      database:
        condition: service_healthy
      chromedriver:
        condition: service_started
    ports:
      - "80:80"
    environment:
      SIMPLETEST_BASE_URL: 'http://drupal'
      SIMPLETEST_DB: 'mysql://database:database@database/database'
      MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", { "chromeOptions": { "w3c": false } }, "http://chromedriver:4444/wd/hub"]'
    volumes:
      - ./html:/var/www/html

  database:
    image: mariadb:latest
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: database
      MARIADB_USER: database
      MARIADB_PASSWORD: database
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 100

  chromedriver:
    image: robcherry/docker-chromedriver:latest
    container_name: chromedriver
    environment:
      CHROMEDRIVER_WHITELISTED_IPS: ""
      CHROMEDRIVER_URL_BASE: "/wd/hub"
    security_opt:
      - seccomp:unconfined
    ports:
      - "4444:4444"
      - "9515:9515"
    ulimits:
      core:
        soft: -1
        hard: -1
    entrypoint: ["/usr/local/bin/supervisord", "-c", "/etc/supervisord.conf"]
